CREATE TABLE SALESPEOPLE (
    SNUM INT PRIMARY KEY,
    SNAME VARCHAR(255) NOT NULL,
    CITY VARCHAR(255),
    COMM DECIMAL(4, 2)
);
CREATE TABLE CUST (
    CNUM INT PRIMARY KEY,
    CNAME VARCHAR(255) NOT NULL,
    CITY VARCHAR(255),
    RATING INT,
    SNUM INT,
    FOREIGN KEY (SNUM) REFERENCES SALESPEOPLE(SNUM)
);
CREATE TABLE ORDERS (
    ONUM INT PRIMARY KEY,
    AMT DECIMAL(10, 2),
    ODATE DATE,
    CNUM INT,
    SNUM INT,
    FOREIGN KEY (CNUM) REFERENCES CUST(CNUM),
    FOREIGN KEY (SNUM) REFERENCES SALESPEOPLE(SNUM)
);mysql -u root -p dbname < 01_create_tables.sql
mysql -u root -p dbname < 02_insert_data.sql


